[package]
name = "plan-pushdown-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
serde = { workspace = true }
ndc-models = { workspace = true }
schemars = { workspace = true }

[dev-dependencies]
goldenfile = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
